//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MVCAuthorization.Models
{
	public partial class Account
	{
		public int Id { get; set; }

		[Required]
		[Display(Name = "Username")]
		[StringLength(30, MinimumLength = 2,
			ErrorMessage = "The username must be more than 2 and less than 30 characters long.")]
		[RegularExpression(@"^[a-zA-Z]*$",
			ErrorMessage = "Username must contain only latin characters.")]
		public string Username { get; set; }

		[Required]
		[DataType(DataType.Password)]
		[Display(Name = "Password")]
		[StringLength(100, MinimumLength = 6,
			ErrorMessage = "The password must be more than 6 and less than 100 characters long.")]
		[RegularExpression(@"^(?=.*\d)(?=.*[A-Z]).*",
			ErrorMessage = "Password must contain at least one uppercase letter and one digit.")]
		public string Password { get; set; }

		[Required]
		[Display(Name = "Sex")]
		public string Sex { get; set; }

		[Required]
		[Display(Name = "Country")]
		public int CountryId { get; set; }
	}
}
